name: Craig Calder
favicon: null
layout_spectrum: 0.5207356428727508
typography_spectrum: 0.7118531239684671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8533420965541154
  lightness: 0.7811617774423212
  saturation: 0.5215714634396136
  rhythmicContrast: 0.953766297083348
purpose: []
